version: "3"
services:
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        image: leninec/latest
        ports:
            - "2931:2931"
        volumes:
            - database:/data

volumes:
    database:
